// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCS5NaKjctxJNXdEiWHIuEMzjiB3UnVFs',
    appId: '1:971623585311:web:2c6f0aa2f944ba4d7ba72a',
    messagingSenderId: '971623585311',
    projectId: 'lashapp-e948e',
    authDomain: 'lashapp-e948e.firebaseapp.com',
    storageBucket: 'lashapp-e948e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnUGhMoa-NUdV5z-b6UO_1D1vn2lRT3YQ',
    appId: '1:971623585311:android:c146f8db5c0c14437ba72a',
    messagingSenderId: '971623585311',
    projectId: 'lashapp-e948e',
    storageBucket: 'lashapp-e948e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxRc0VL_xwg0FOHr8fqqV-XgMV_e427fs',
    appId: '1:971623585311:ios:36165d8e73da2ec37ba72a',
    messagingSenderId: '971623585311',
    projectId: 'lashapp-e948e',
    storageBucket: 'lashapp-e948e.appspot.com',
    iosClientId: '971623585311-mv1fjrmu62c18jh51e92lhvhocl31u4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxRc0VL_xwg0FOHr8fqqV-XgMV_e427fs',
    appId: '1:971623585311:ios:a0a78791e7435d647ba72a',
    messagingSenderId: '971623585311',
    projectId: 'lashapp-e948e',
    storageBucket: 'lashapp-e948e.appspot.com',
    iosClientId: '971623585311-h5bm1cd34ben595fcnfv071clr73daab.apps.googleusercontent.com',
    iosBundleId: 'com.example.lashApp.RunnerTests',
  );
}
